### ISSUE TITLE
DIV for select box not terminated

### ISSUE THREAD

**Issue by dpjanes** [django-crispy-forms/crispy-tailwind#156] opened 2024-02-07 14:46 UTC
In [ `templates/tailwind/field.html`](https://github.com/django-crispy-forms/crispy-tailwind/blob/main/crispy_tailwind/templates/tailwind/field.html) none of the `div`s are terminated (for release 1.0.1),

I think there's some mismatch between how you are doing it in the layout folder and in this template - I suspect it makes more sense to move all the closing DIVs back up to this file. In the `select.html` there is no  `</div>` whereas I think in the radio and checkboxes there are.

**Comment by dpjanes** [comment] 2024-02-07 14:47
Basically at this point, crispy-tailwind will not work for `<select>` any more! So pretty serious.

**Comment by justinmayer** [comment] 2024-02-07 14:53
Hey David. I can't test this right now, but if this is indeed an issue, then I am fairly certain that it is a duplicate of #153, so let's continue the discussion there.

As an aside, it's always helpful to check open PRs before filing new issues. Thanks! 😊

**Closed by justinmayer** 2024-02-07 14:53 UTC

**Comment by dpjanes** [comment] 2024-02-07 14:55
My apologies, I did look but obviously I am blind.
