### ISSUE TITLE
Please release crispy-tailwind on PyPI or remove pip install from instructions

### ISSUE THREAD

**Issue by pydanny** [django-crispy-forms/crispy-tailwind#23] opened 2020-06-08 17:08 UTC
Your instructions are inaccurate, please consider updating them to reflect the current status of the project.

**Comment by carltongibson** [comment] 2020-06-09 05:15
Hi @pydanny 👋 It’s coming.

Duplicate of #17.

**Closed by carltongibson** 2020-06-09 05:15 UTC
